"""v0.88 #11 — render the dashboard as a minimal markdown summary.

The full HTML dashboard at `.research_hub/dashboard.html` is desktop-only:
file:// links don't work inside Obsidian on iOS. This module writes a
companion `.research_hub/dashboard-summary.md` that mirrors the top-line
metrics in plain markdown so the user can open it from `_HOME.md` on
mobile.

Mirrors the structure of the HTML dashboard's Overview tab:
- Cluster paper counts
- NotebookLM brief counts
- Summarize-status backlog (per cluster)
- Doctor status (top-line green/warn/fail)
- Timestamp
"""

from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path


_FRONTMATTER_RE = re.compile(r"\A---\n(.*?)\n---", re.DOTALL)
_SUMMARIZE_STATUS_RE = re.compile(r'^summarize_status:\s*"?([^"\n]+)"?\s*$', re.MULTILINE)
_STATUS_RE = re.compile(r'^status:\s*"?([^"\n]+)"?\s*$', re.MULTILINE)


def render_dashboard_markdown_summary(cfg) -> str:
    """Build the dashboard summary markdown body. Returns the text — caller writes."""
    from research_hub.clusters import ClusterRegistry

    vault_root = Path(cfg.root)
    registry = ClusterRegistry(cfg.clusters_file)
    clusters = [c for c in registry.list() if (c.slug or "").strip()]

    now_utc = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    lines: list[str] = [
        "---",
        "type: dashboard-summary",
        f"generated_at: {now_utc}",
        "---",
        "",
        "# Dashboard summary",
        "",
        "Mobile-friendly mirror of `dashboard.html`. Regenerated by",
        "`research-hub dashboard --markdown-summary`.",
        "",
        "## Clusters",
        "",
    ]

    if not clusters:
        lines.append("(no clusters)")
    else:
        lines.append("| cluster | papers | unread | brief? | pending summary |")
        lines.append("|---|---:|---:|---|---:|")
        total_papers = total_unread = total_pending = 0
        total_briefs_clusters = 0
        for cluster in clusters:
            slug = cluster.slug
            stats = _cluster_stats(vault_root, slug)
            brief_marker = "✅" if stats["brief_exists"] else "—"
            if stats["brief_exists"]:
                total_briefs_clusters += 1
            lines.append(
                f"| [[{slug}/00_overview\\|{slug}]] | {stats['papers']} | "
                f"{stats['unread']} | {brief_marker} | {stats['pending_summary']} |"
            )
            total_papers += stats["papers"]
            total_unread += stats["unread"]
            total_pending += stats["pending_summary"]
        lines.append(f"| **total** | **{total_papers}** | **{total_unread}** | "
                     f"{total_briefs_clusters}/{len(clusters)} | **{total_pending}** |")

    lines.extend([
        "",
        "## Backlog",
        "",
    ])
    if not clusters:
        lines.append("(no backlog data)")
    else:
        backlog_total = sum(
            _cluster_stats(vault_root, c.slug)["pending_summary"] for c in clusters
        )
        if backlog_total == 0:
            lines.append("Papers awaiting summary: **0** ✅")
        else:
            lines.append(f"Papers awaiting summary: **{backlog_total}**")
            lines.append("")
            lines.append("Run `research-hub paper summarize --pending` to clear.")

    lines.extend([
        "",
        "## Quick commands",
        "",
        "- `research-hub doctor` — health check",
        "- `research-hub vault rebuild-overviews` — refresh cluster overviews + MOCs + _HOME.md",
        "- `research-hub paper summarize --pending` — fill placeholder sections",
        "- `research-hub dashboard --open` — open full HTML dashboard (desktop only)",
        "",
    ])
    return "\n".join(lines)


def write_dashboard_markdown_summary(cfg, *, out_path: Path | None = None) -> Path:
    """Write the markdown summary to disk. Default location is
    `<vault>/.research_hub/dashboard-summary.md` so it stays next to the
    HTML dashboard but is reachable from Obsidian via relative path."""
    target = out_path or Path(cfg.root) / ".research_hub" / "dashboard-summary.md"
    target.parent.mkdir(parents=True, exist_ok=True)
    body = render_dashboard_markdown_summary(cfg)
    target.write_text(body, encoding="utf-8")
    return target


def _cluster_stats(vault_root: Path, slug: str) -> dict:
    raw = vault_root / "raw" / slug
    hub = vault_root / "hub" / slug
    stats = {
        "papers": 0,
        "unread": 0,
        "pending_summary": 0,
        "brief_exists": False,
    }
    if raw.exists():
        for note in raw.glob("*.md"):
            if note.name in {"00_overview.md", "index.md"}:
                continue
            stats["papers"] += 1
            try:
                text = note.read_text(encoding="utf-8", errors="ignore")
            except OSError:
                continue
            fm = _FRONTMATTER_RE.search(text)
            fm_body = fm.group(1) if fm else ""
            status_match = _STATUS_RE.search(fm_body)
            if status_match and status_match.group(1).strip().lower() == "unread":
                stats["unread"] += 1
            sum_match = _SUMMARIZE_STATUS_RE.search(fm_body)
            if sum_match and sum_match.group(1).strip().lower() == "pending":
                stats["pending_summary"] += 1
    if hub.exists():
        for _ in hub.glob("notebooklm-brief-*.md"):
            stats["brief_exists"] = True
            break
    return stats
